name: "build&test"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install flake8 black

      - name: Run linting check
        run: flake8 ./tinyget

      - name: Run code formatting check
        run: black ./tinyget --check  --verbose .

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/*.whl

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Install package
        run: pip install dist/*.whl

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest